version: "3.8"

services:
  web-app:
    build: ./web-app
    ports:
      - "5000:5000"         # External access http://localhost:5000
    depends_on:
      - ml-client           # Start the ml-client service first

  ml-client:
    build: ./machine-learning-client
    ports:
      - "5001:5001"         # Provide the /analyze interface for web-app access
