
version: '3.9'

services:
  mongo:
    image: mongo:5
    container_name: emotion-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  client:
    build: ./machine-learning-client
    container_name: emotion-client
    depends_on:
      - mongo
    volumes:
      - ./machine-learning-client/images:/app/images  # 映射图像文件
      - /dev:/dev
    environment:
      - MONGO_URI=mongodb://mongo:27017
    restart: unless-stopped
    privileged: true

  web-app:
    build: ./web-app
    container_name: emotion-web
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - ./machine-learning-client/images:/machine-learning-client/images
    restart: unless-stopped

volumes:
  mongo-data: