version: "3.8"

services:
  web-app:
    build: ./web-app
    ports:
      - "5000:5000"         # 外部访问 http://localhost:5000
    depends_on:
      - ml-client           # 先启动 ml-client 服务

  ml-client:
    build: ./machine-learning-client
    ports:
      - "5001:5001"         # 提供 /analyze 接口，供 web-app 访问
