version: "3.8"

services:
  web-app:
    build: ./web-app
    ports:
      - "8081:5000"         # External access at http://localhost:8081
    depends_on:
      - ml-client           # Start ml-client service first

  ml-client:
    build: ./machine-learning-client
    ports:
      - "5002:5002"         # Provides /analyze endpoint for web-app
