version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  client:
    build: ./machine-learning-client
    depends_on:
      - mongodb
    devices:
      - "/dev/video0:/dev/video0"

  web:
    build: ./web-app
    depends_on:
      - mongodb
    ports:
      - "5000:5000"
