version: "3.8"

services:
  web-app:
    build: ./web-app
    ports:
      - "8888:8888"
    depends_on:
      - ml-client
      - mongo-db


  ml-client:
    build: ./machine-learning-client
    ports:
      - "5001:5001"
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"


volumes:
  mongo-data: