name: CI for machine-learning-client

on:
  push:
    paths:
      - "machine-learning-client/**"
  pull_request:
    paths:
      - "machine-learning-client/**"

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: machine-learning-client

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint black pytest pytest-cov mongomock

      - name: Lint with pylint
        working-directory: machine-learning-client
        run: |
          python -m pylint app tests --exit-zero

      - name: Format with black
        run: |
          black --check app tests

      - name: Run tests with coverage
        run: |
          pytest --cov=app tests

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: machine-learning-client/.coverage