name: ML Client CI

on:
  push:
    paths:
      - 'machine-learning-client/**'
  pull_request:
    paths:
      - 'machine-learning-client/**'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: machine-learning-client
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint black pytest pytest-cov mongomock

      - name: Lint with pylint
        working-directory: machine-learning-client
        run: |
          python -m pylint app tests --exit-zero

      - name: Format with black
        working-directory: machine-learning-client
        run: |
          black --check app tests

      - name: Run unit tests with coverage
        working-directory: machine-learning-client
        run: |
          pytest --cov=app --cov-report=term-missing