name: lint-free

on: [push, pull_request]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        subdir: [web-app, machine-learning-client]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install pipenv & dependencies
        if: ${{ hashFiles(format('{0}/**/*.py', matrix.subdir)) != '' }}
        working-directory: ${{ matrix.subdir }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          
          echo "Locking dependencies (if needed)..."
          pipenv lock --clear || echo "Locking failed, maybe already locked."
          
          echo "Installing dependencies from Pipfile.lock..."
          pipenv install --deploy --ignore-pipfile || (
            echo "⚠️ Pipenv install failed. Trying pip fallback..." &&
            pip install -r <(pipenv lock -r)
          )

      - name: Lint with pylint
        if: ${{ hashFiles(format('{0}/**/*.py', matrix.subdir)) != '' }}
        working-directory: ${{ matrix.subdir }}
        run: |
          python -m pip install pylint
          find . -name "*.py" | xargs pylint --rcfile=../.pylintrc --exit-zero
      - name: Format with black
        if: ${{ hashFiles(format('{0}/**/*.py', matrix.subdir)) != '' }}
        working-directory: ${{ matrix.subdir }}
        run: |
          pipenv run black --diff --check . || echo 