name: ML Client CI

on:
  push:
    branches: [ main ]
    paths:
      - 'machine-learning-client/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'machine-learning-client/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      working-directory: ./machine-learning-client
      run: |
        python -m pip install --upgrade pip
        # Check if Pipfile exists and use pipenv if it does, otherwise use requirements.txt
        if [ -f "Pipfile" ]; then
          pip install pipenv
          pipenv install --dev --system
        else
          pip install -r requirements.txt
        fi
        # Ensure all dependencies are installed for linting
        pip install pylint black pytest pytest-cov
        
    - name: Run linters
      working-directory: ./machine-learning-client
      run: |
        black . --check
        pylint --rcfile=../.pylintrc --ignore-patterns="test_.*\.py" *.py
        
    - name: Run tests with coverage
      working-directory: ./machine-learning-client
      run: |
        pytest --cov=. --cov-report=xml --cov-report=term
        
    - name: Check coverage threshold
      working-directory: ./machine-learning-client
      run: |
        python -c "import sys, xml.etree.ElementTree as ET; sys.exit(0 if float(ET.parse('coverage.xml').getroot().get('line-rate')) >= 0.8 else 1)" 