name: Web App CI

on:
  push:
    branches: [ main ]
    paths:
      - 'web-app/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'web-app/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      working-directory: ./web-app
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Ensure all dependencies are installed for linting
        pip install pylint black pytest pytest-cov pytest-flask
        
    - name: Run linters
      working-directory: ./web-app
      run: |
        black . --check
        pylint --disable=C0111,C0103,W0611,E0401 --ignore-patterns="test_.*\.py" *.py
        
    - name: Run tests with coverage
      working-directory: ./web-app
      run: |
        pytest --cov=. --cov-report=xml --cov-report=term
        
    - name: Check coverage threshold
      working-directory: ./web-app
      run: |
        python -c "import sys, xml.etree.ElementTree as ET; sys.exit(0 if float(ET.parse('coverage.xml').getroot().get('line-rate')) >= 0.8 else 1)" 